import { Npc } from './components/Npc';
import { SceneName } from './enums/SceneNames';
import { Door } from './components/Door';
import { CollisionStrategy } from 'grid-engine';
import GameScene from "./GameScene"
import { LayerType } from './enums/LayerType';
import { getElement } from '../data/elements';
import { openQuiz } from '../ui/QuizOverlay';

// The three starter Elementals that roam the open town plaza. The other four
// live inside the Lab and Shop (see LabScene / ShopScene) so exploring the
// buildings is rewarded. Coordinates are walkable grass, clear of the paths,
// building fronts and decorative trees.
const MONSTER_SPAWNS: { elementId: string; x: number; y: number }[] = [
    { elementId: 'hydrogen', x: 8,  y: 13 },
    { elementId: 'helium',   x: 13, y: 14 },
    { elementId: 'carbon',   x: 18, y: 13 },
];

// Each building's walkable door tile (bottom of the painted doorway) and the
// room it leads into. Generated by tools/gen_town.py — keep in sync with it.
const TOWN_DOORS: { x: number; y: number; scene: SceneName; label: string }[] = [
    { x: 6,  y: 8, scene: SceneName.Shop, label: 'ENTER ▶' },
    { x: 13, y: 8, scene: SceneName.Lab,  label: 'ENTER ▶' },
    { x: 23, y: 8, scene: SceneName.Home, label: 'ENTER ▶' },
];

// Name plaques drawn over the reused "MARKET" facades (world-pixel centres,
// one per storefront). Sizes/positions verified against tools/gen_town.py.
const TOWN_SIGNS: { text: string; cx: number; cy: number }[] = [
    { text: 'SHOP', cx: 96,  cy: 88 },
    { text: 'LAB',  cx: 208, cy: 88 },
    { text: 'HOME', cx: 360, cy: 88 },
];


export default class TestScene extends GameScene {
    constructor() {
        super(SceneName.Test, 13, 12, [LayerType.Floor, LayerType.Walls])

        this.imageNames = {
            Perli: `${SceneName.Test}_perli`,
            Veterinary: 'test_veterinary',
            Map: 'test_map',
        }

        this.tilemapJSONPath = '../assets/tilemap/test_map.json'
        this.imageMapDefaultPath = '../assets/tiles/'
        this.imageMapNames = {
            modern_exterior: {
                name: "modern_exterior",
            },
        }

        this.gridEngineSettings = {
            startPosition: {
                x: 13,
                y: 12
            },
            scale: 5,
            characterCollisionStrategy: CollisionStrategy.BLOCK_ONE_TILE_AHEAD,
            layerOverlay: false
        }
    }

    preload(): void {
        super.preload()
        super.loadAvatarSpritesheet()
        super.loadMapImages()
        this.loadObjectImages()
    }

    loadObjectImages(): void {
        this.load.spritesheet(
            this.imageNames.Veterinary,
            '../assets/Characters/NPCs_1.png',
            {
                frameWidth: 32,
                frameHeight: 64
            }
        )
    }

    create(): void {
        super.create()

        // Name plaques over each storefront (covers the reused "MARKET" art).
        TOWN_SIGNS.forEach(s => this.drawSign(s.text, s.cx, s.cy))

        // One labelled door per building: walk up to it to enter that room.
        TOWN_DOORS.forEach(d => {
            const door = new Door({
                scene: this, xPosition: d.x, yPosition: d.y, nextScene: d.scene
            })
            this.addFloatingLabel(door.name, d.label, '#ffe066')
        })
    }

    // Draws a navy/gold shop plaque (game palette) centred on a building sign.
    private drawSign(text: string, cx: number, cy: number): void {
        const w = 62, h = 17
        const g = this.add.graphics().setDepth(500)
        g.fillStyle(0x10203a, 1).fillRoundedRect(cx - w / 2, cy - h / 2, w, h, 3)
        g.lineStyle(1, 0xffd166, 1).strokeRoundedRect(cx - w / 2, cy - h / 2, w, h, 3)
        this.add.text(cx, cy - 1, text, {
            fontFamily: 'monospace',
            fontSize: '11px',
            fontStyle: 'bold',
            color: '#ffd166',
        }).setOrigin(0.5).setDepth(501)
    }

    createNpcs(): void {

        // One monster NPC per starter element. Face it and press E to start its
        // quiz. A floating element symbol makes each one identifiable.
        MONSTER_SPAWNS.forEach(spawn => {
            const element = getElement(spawn.elementId);
            if (!element) return;

            const monster = new Npc({
                scene: this,
                xPosition: spawn.x,
                yPosition: spawn.y,
                texture: this.imageNames.Veterinary,
                scale: 0.7,
                tint: element.tint,
                action: () => { openQuiz(spawn.elementId); },
                walkingAnimationMapping: 0,
            });
            this.addFloatingLabel(monster.name, element.symbol, '#ffffff');
        });
    }

    // Places a small always-on text label above a character (monster or door).
    private addFloatingLabel(charName: string, text: string, color: string): void {
        const sprite = this.gridEngine.getSprite(charName);
        if (!sprite) return;
        const top = sprite.getTopCenter();
        this.add.text(top.x, top.y - 2, text, {
            fontFamily: 'monospace',
            fontSize: '9px',
            color,
            backgroundColor: '#000000aa',
            padding: { x: 2, y: 1 },
        }).setOrigin(0.5, 1).setDepth(9999);
    }

    update(): void {
        super.update()
    }
}