import { SceneName } from './enums/SceneNames';
import { Door } from './components/Door';
import { CollisionStrategy } from 'grid-engine';
import GameScene from "./GameScene"
import { LayerType } from './enums/LayerType';

// The Elementals that live outdoors. Hydrogen + Oxygen sit on the shore of the
// town lake (the lake is water, H2O); Neon roams the plaza like a glowing sign.
// The rest live inside the venues (Hardware/Hannaford/Auto/Library) so exploring
// the town is rewarded. Coordinates are walkable grass, clear of paths/lake.
const MONSTER_SPAWNS: { elementId: string; x: number; y: number }[] = [
    { elementId: 'hydrogen', x: 23, y: 16 },
    { elementId: 'oxygen',   x: 23, y: 19 },
    { elementId: 'neon',     x: 16, y: 14 },
];

// Each venue's walkable door tile (bottom of the painted doorway) and the room
// it leads into. Generated by tools/gen_town.py — keep in sync with its
// printed "door tiles". Gray, Maine (04039) storefronts.
const TOWN_DOORS: { x: number; y: number; scene: SceneName; label: string }[] = [
    { x: 6,  y: 8,  scene: SceneName.Hardware,  label: 'ENTER ▶' },
    { x: 16, y: 8,  scene: SceneName.Hannaford, label: 'ENTER ▶' },
    { x: 24, y: 8,  scene: SceneName.Library,   label: 'ENTER ▶' },
    { x: 34, y: 8,  scene: SceneName.Home,      label: 'ENTER ▶' },
    { x: 5,  y: 20, scene: SceneName.Auto,      label: 'ENTER ▶' },
];

// Name plaques drawn over the reused facades (world-pixel centres, one per
// storefront). cx = (townCol + width/2) * 16, cy = (townRow + 4.5) * 16.
// Verified against the PLACEMENTS in tools/gen_town.py.
const TOWN_SIGNS: { text: string; cx: number; cy: number }[] = [
    { text: 'HARDWARE',  cx: 80,  cy: 88 },
    { text: "HANNAFORD", cx: 240, cy: 88 },
    { text: 'LIBRARY',   cx: 392, cy: 88 },
    { text: 'HOME',      cx: 544, cy: 88 },
    { text: 'AUTO',      cx: 80,  cy: 280 },
];

// The decorative lake (matches LAKE in tools/gen_town.py): a rectangle of
// blocking water cells, drawn blue here since the tiles have no real water art.
const LAKE = { x: 24, y: 15, w: 14, h: 7 };  // in tiles


export default class TestScene extends GameScene {
    constructor() {
        super(SceneName.Test, 18, 12, [LayerType.Floor, LayerType.Walls])

        this.imageNames = {
            Perli: `${SceneName.Test}_perli`,
            Veterinary: 'test_veterinary',
            Map: 'test_map',
        }

        this.tilemapJSONPath = '../assets/tilemap/test_map.json'
        this.imageMapDefaultPath = '../assets/tiles/'
        this.imageMapNames = {
            modern_exterior: {
                name: "modern_exterior",
            },
        }

        this.gridEngineSettings = {
            startPosition: {
                x: 18,
                y: 12
            },
            scale: 5,
            characterCollisionStrategy: CollisionStrategy.BLOCK_ONE_TILE_AHEAD,
            layerOverlay: false
        }
    }

    preload(): void {
        super.preload()
        super.loadAvatarSpritesheet()
        super.loadMapImages()
        this.loadObjectImages()
    }

    loadObjectImages(): void {
        this.load.spritesheet(
            this.imageNames.Veterinary,
            '../assets/Characters/NPCs_1.png',
            {
                frameWidth: 32,
                frameHeight: 64
            }
        )
        this.loadElementalArt(MONSTER_SPAWNS.map(s => s.elementId))
        // Neonu Reeves, the disco bug — a flavor NPC, not an Elemental.
        this.load.image('neonu_reeves', '../assets/elementals/neonu-reeves.png')
    }

    create(): void {
        super.create()

        // The town lake — blue water behind the sprites (real tiles have no
        // water art, so we paint it). The cells are already blocking (gen_town).
        this.drawLake()

        // Name plaques over each storefront (covers the reused facade art).
        TOWN_SIGNS.forEach(s => this.drawSign(s.text, s.cx, s.cy))

        // One labelled door per building: walk up to it to enter that room.
        TOWN_DOORS.forEach(d => {
            const door = new Door({
                scene: this, xPosition: d.x, yPosition: d.y, nextScene: d.scene
            })
            this.addFloatingLabel(door.name, d.label, '#ffe066')
        })
    }

    // Draws a navy/gold shop plaque (game palette) centred on a building sign.
    // The box auto-sizes to the label so long names like "HANNAFORD" fit.
    private drawSign(text: string, cx: number, cy: number): void {
        const w = Math.max(62, text.length * 8 + 14), h = 17
        const g = this.add.graphics().setDepth(500)
        g.fillStyle(0x10203a, 1).fillRoundedRect(cx - w / 2, cy - h / 2, w, h, 3)
        g.lineStyle(1, 0xffd166, 1).strokeRoundedRect(cx - w / 2, cy - h / 2, w, h, 3)
        this.add.text(cx, cy - 1, text, {
            fontFamily: 'monospace',
            fontSize: '11px',
            fontStyle: 'bold',
            color: '#ffd166',
        }).setOrigin(0.5).setDepth(501)
    }

    // Paints the lake: rippled blue fill over the blocking water cells, plus a
    // "LAKE" label. Sits above the ground tiles but below the floating labels;
    // the dog can never walk onto it (those cells collide), so depth is safe.
    private drawLake(): void {
        const px = LAKE.x * 16, py = LAKE.y * 16, pw = LAKE.w * 16, ph = LAKE.h * 16
        const g = this.add.graphics().setDepth(50)
        g.fillStyle(0x2a6fb0, 1).fillRoundedRect(px, py, pw, ph, 10)
        g.lineStyle(2, 0x1c4f80, 1).strokeRoundedRect(px, py, pw, ph, 10)
        g.fillStyle(0x5aa0d8, 0.5)
        for (let i = 0; i < 3; i++) {
            g.fillRoundedRect(px + 12, py + 14 + i * 22, pw - 24, 6, 3)
        }
        this.add.text(px + pw / 2, py + ph / 2, 'LAKE', {
            fontFamily: 'monospace',
            fontSize: '12px',
            fontStyle: 'bold',
            color: '#eaf4ff',
        }).setOrigin(0.5).setDepth(51)
    }

    createNpcs(): void {
        // One Elemental per outdoor spawn — real art if it has any, else a tinted
        // placeholder. Face it and press E to start its quiz (see spawnElemental).
        MONSTER_SPAWNS.forEach(spawn => this.spawnElemental(spawn.elementId, spawn.x, spawn.y));

        // Neonu Reeves grooves around the plaza. No quiz — he just exists.
        this.spawnWanderingNpc('neonu_reeves', 16, 17, 'Neonu ♪');
    }

    update(): void {
        super.update()
    }
}