import { SceneName } from './enums/SceneNames';
import { Door } from './components/Door';
import { drawDoorCue } from './components/DoorCue';
import { CollisionStrategy } from 'grid-engine';
import GameScene from "./GameScene"
import { LayerType } from './enums/LayerType';
import GlobalInfo from '../GlobalInfo';

// The Elementals that live outdoors in town. Hydrogen sits on the shore of the
// town lake; Neon roams the plaza like a glowing sign. Oxygen, Carbon and
// Nitrogen now live wild up in the North Woods. The rest live inside the venues.
// Coordinates are walkable grass, clear of paths/lake.
const MONSTER_SPAWNS: { elementId: string; x: number; y: number }[] = [
    { elementId: 'hydrogen', x: 23, y: 16 },
    { elementId: 'neon',     x: 16, y: 14 },
];

// Each venue's walkable door tile (bottom of the painted doorway) and the room
// it leads into. Generated by tools/gen_town.py — keep in sync with its
// printed "door tiles". Gray, Maine (04039) storefronts.
const TOWN_DOORS: { x: number; y: number; scene: SceneName }[] = [
    { x: 5,  y: 8,  scene: SceneName.Hardware },
    { x: 15, y: 8,  scene: SceneName.Hannaford },
    { x: 24, y: 8,  scene: SceneName.Library },
    { x: 34, y: 8,  scene: SceneName.Home },
    { x: 5,  y: 20, scene: SceneName.Auto },
    // North trail out of town → the woods & meadow (walk up the gap between the
    // hardware and grocery stores). Pad is the tile just south, like any door.
    { x: 9,  y: 0,  scene: SceneName.Woods },
];

// Real building art (cropped tight to its content) overlaid on the invisible
// storefront footprints from tools/gen_town.py. Each image is anchored
// bottom-centre over its door tile and scaled so it spans `widthTiles` tiles
// wide; every storefront has its name painted on, so no sign plaques are needed.
// The wide storefronts are sized up so they don't look small beside the square
// hardware store — keep widthTiles in sync with WIDTH_TILES in gen_town.py.
const BUILDINGS: { key: string; oy: number; h: number; doorX: number; widthTiles: number }[] = [
    { key: 'bld_hardware', oy: 1,  h: 8, doorX: 5,  widthTiles: 6.3 },
    { key: 'bld_grocery',  oy: 1,  h: 8, doorX: 15, widthTiles: 9.8 },
    { key: 'bld_library',  oy: 1,  h: 8, doorX: 24, widthTiles: 8.6 },
    { key: 'bld_home',     oy: 1,  h: 8, doorX: 34, widthTiles: 9.8 },
    { key: 'bld_auto',     oy: 13, h: 8, doorX: 5,  widthTiles: 9.8 },
];

// The decorative lake (matches LAKE in tools/gen_town.py): a rectangle of
// blocking water cells, drawn blue here since the tiles have no real water art.
const LAKE = { x: 24, y: 15, w: 14, h: 7 };  // in tiles


export default class TestScene extends GameScene {
    constructor() {
        super(SceneName.Test, 18, 12, [LayerType.Floor, LayerType.Walls])

        this.imageNames = {
            Perli: `${SceneName.Test}_perli`,
            Veterinary: 'test_veterinary',
            Map: 'test_map',
        }

        this.tilemapJSONPath = '../assets/tilemap/test_map.json'
        this.imageMapDefaultPath = '../assets/tiles/'
        this.imageMapNames = {
            modern_exterior: {
                name: "modern_exterior",
            },
        }

        this.gridEngineSettings = {
            startPosition: {
                x: 18,
                y: 12
            },
            scale: 5,
            characterCollisionStrategy: CollisionStrategy.BLOCK_ONE_TILE_AHEAD,
            layerOverlay: false
        }
    }

    preload(): void {
        super.preload()
        super.loadAvatarSpritesheet()
        super.loadMapImages()
        this.loadObjectImages()
    }

    loadObjectImages(): void {
        this.load.spritesheet(
            this.imageNames.Veterinary,
            '../assets/Characters/NPCs_1.png',
            {
                frameWidth: 32,
                frameHeight: 64
            }
        )
        this.loadElementalArt(MONSTER_SPAWNS.map(s => s.elementId))
        // Storefront art (backgrounds already removed) overlaid on the map.
        BUILDINGS.forEach(b => this.load.image(b.key, `../assets/buildings/${b.key.replace('bld_', '')}.png`))
    }

    create(): void {
        super.create()

        // The town lake — blue water behind the sprites (real tiles have no
        // water art, so we paint it). The cells are already blocking (gen_town).
        this.drawLake()

        // Real storefront art over the invisible building footprints.
        BUILDINGS.forEach(b => this.drawBuilding(b))

        // Secret teacher-portal entrance: an invisible long-press hotspot on the
        // library's sign. Students never see it; a teacher press-and-holds it.
        const library = BUILDINGS.find(b => b.key === 'bld_library')
        if (library) this.addTeacherPortalTile(library)

        // One door per building: step onto the square outside it (one tile south)
        // to enter. A glowing "ENTER ▲" pad marks each entrance so new players can
        // tell buildings are enterable — most Elementals live inside them.
        TOWN_DOORS.forEach(d => {
            new Door({
                scene: this, xPosition: d.x, yPosition: d.y, nextScene: d.scene
            })
            const label = d.scene === SceneName.Woods ? 'WOODS' : 'ENTER'
            drawDoorCue(this, d.x, d.y + 1, label, '▲')
        })
    }

    // Overlay one storefront image: anchored bottom-centre on its door tile and
    // scaled so the art spans `widthTiles` tiles wide (aspect preserved). Depth 1
    // keeps it above the ground tiles but below the characters (depth 10), so the
    // dog walks in front of the shop.
    private drawBuilding(b: { key: string; oy: number; h: number; doorX: number; widthTiles: number }): void {
        const src = this.textures.get(b.key).getSourceImage() as HTMLImageElement
        const scale = (b.widthTiles * 16) / src.width
        this.add.image((b.doorX + 0.5) * 16, (b.oy + b.h) * 16, b.key)
            .setOrigin(0.5, 1)
            .setScale(scale)
            .setDepth(1)
    }

    // An invisible input zone over the top (the sign) of the library building.
    // Press and hold it for ~1s to open the teacher portal — a hidden entrance
    // students won't stumble into (and it's gated by Google login + the teacher
    // claim anyway, so being found is harmless). A quick tap just walks the dog.
    //
    // NOTE: we cancel only on pointer *release* (global), never on pointer-out.
    // Holding the spot also tap-walks the dog toward the library, which scrolls
    // the camera under a still finger; cancelling on pointer-out would kill the
    // hold the instant the camera moved. A gold ring "charges" while held so the
    // teacher gets feedback that the secret spot is active.
    private addTeacherPortalTile(b: { key: string; oy: number; h: number; doorX: number; widthTiles: number }): void {
        const HOLD_MS = 1000
        const src = this.textures.get(b.key).getSourceImage() as HTMLImageElement
        const drawnH = (b.widthTiles * 16) / src.width * src.height
        const topY = (b.oy + b.h) * 16 - drawnH
        const zx = (b.doorX + 0.5) * 16
        const zy = topY + drawnH * 0.2
        const zw = b.widthTiles * 16 * 0.7
        const zh = drawnH * 0.36
        const zone = this.add.zone(zx, zy, zw, zh).setInteractive()

        let timer: ReturnType<typeof setTimeout> | undefined
        let cue: Phaser.GameObjects.Rectangle | undefined
        const cancel = (): void => {
            if (timer) { clearTimeout(timer); timer = undefined }
            if (cue) { cue.destroy(); cue = undefined }
        }
        zone.on('pointerdown', () => {
            cancel()
            if (GlobalInfo._gameProgress.inDialogue) return   // not while a quiz/dialog is open
            cue = this.add.rectangle(zx, zy, zw, zh).setStrokeStyle(2, 0xffd166, 0.9).setDepth(60)
            cue.setAlpha(0)
            this.tweens.add({ targets: cue, alpha: 0.9, duration: HOLD_MS, ease: 'Sine.easeIn' })
            timer = setTimeout(() => { window.location.href = 'teacher.html' }, HOLD_MS)
        })
        this.input.on('pointerup', cancel)   // any release anywhere cancels the hold
    }

    // Paints the lake: rippled blue fill over the blocking water cells, plus a
    // "LAKE" label. Sits above the ground tiles but below the floating labels;
    // the dog can never walk onto it (those cells collide), so depth is safe.
    private drawLake(): void {
        const px = LAKE.x * 16, py = LAKE.y * 16, pw = LAKE.w * 16, ph = LAKE.h * 16
        const g = this.add.graphics().setDepth(50)
        g.fillStyle(0x2a6fb0, 1).fillRoundedRect(px, py, pw, ph, 10)
        g.lineStyle(2, 0x1c4f80, 1).strokeRoundedRect(px, py, pw, ph, 10)
        g.fillStyle(0x5aa0d8, 0.5)
        for (let i = 0; i < 3; i++) {
            g.fillRoundedRect(px + 12, py + 14 + i * 22, pw - 24, 6, 3)
        }
        this.add.text(px + pw / 2, py + ph / 2, 'LAKE', {
            fontFamily: 'monospace',
            fontSize: '12px',
            fontStyle: 'bold',
            color: '#eaf4ff',
        }).setOrigin(0.5).setDepth(51)
    }

    createNpcs(): void {
        // One Elemental per outdoor spawn — real art if it has any, else a tinted
        // placeholder. Walk within one tile to start its quiz (see spawnElemental).
        MONSTER_SPAWNS.forEach(spawn => this.spawnElemental(spawn.elementId, spawn.x, spawn.y));
    }

    update(): void {
        super.update()
    }
}